<?php

/**
 * @file
 * Contains mailing.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_help().
 */
function mailing_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailing module.
    case 'help.page.mailing':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for mailing to user.') . '</p>';
      return $output;

    default:
  }
}
 
/**
 * Implements hook_mail().
 */
function mailing_mail($key, &$message, $params) {
  switch ($key) {
    case 'mailing_queue':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_cron().
 */
function mailing_cron() {
  /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('mailing_queue'); 
  $queue_mail = \Drupal::queue('mail');
  for ($i=0; $i < 10; $i++) { 
    $item = $queue_mail->claimItem();
    $queue->createItem($item->data['mail']);
    $queue_mail->deleteItem($item);
  }
}
