<?php
/**
 * @file
 * Hooks for status_messager module.
 */

/**
 * Implements hook_theme_registry_alter().
 */
function status_messager_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['path'] = drupal_get_path('module', 'status_messager') . '/templates';
  $theme_registry['status_messages']['variables']['img_close_path'] = base_path() . drupal_get_path('module','status_messager').'/images/close.png';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function status_messager_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'status_messager/modal.from.js';
  $variables['#attached']['drupalSettings']['status_messager'] = \Drupal::config('status_messager.settings')->get();
}
