<?php

/**
 * @file
 * Contains mailing_queue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_cron().
 */
function mailing_queue_cron() {
   /** @var QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var QueueInterface $queue */
  $queue = $queue_factory->get('mail_queue'); 

  $nids = \Drupal::entityQuery('user')
    ->sort('created', 'ASC')
    ->execute();

  $queue_mail = 'SELECT * FROM mailing';
  foreach ($queue_mail as $elem) {
    $user_mails = array();
    $user_mails[] = $elem->mail; 
  }

  foreach ($nids as $user_id) {
    if ($user_id != 1) {
      $user = \Drupal\user\Entity\User::load($user_id);
      if (!(in_array($user_mails, $user->mail->value))) {
        $queue->createItem($user->mail->value); 
      }
    }
  } 
}

