<?php

/**
 * @file
 * Contains mailing_queue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_cron().
 */
function mailing_queue_cron() {

  $queue = \Drupal::queue('mail');
  $count = $queue->numberOfItems();
  $nids = \Drupal::entityQuery('user')
    ->sort('created', 'ASC')
    ->execute();

  if ($count == 0) {
    $queue->createQueue();
    foreach ($nids as $user_id) {
      if ($user_id != 1) {
        $user = \Drupal\user\Entity\User::load($user_id);
        $mail = $user->mail->value;
        $username = $user->name->value;
        if($mail) {
          $queue->createItem(['mail' => $mail,'username' => $username]); 
        }  
      }
    }
  }
}
