<?php

/**
 * @file
 * Contains mailing_queue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Queue\QueueFactory;
use Drupal\Core\Queue\QueueInterface;

/**
 * Implements hook_cron().
 */
function mailing_queue_cron() {

  $queue = \Drupal::queue('mail');
  $count = $queue->numberOfItems();
  $users = entity_load_multiple('user');
  $admin_mail = \Drupal::config('system.site')->get('mail');

  if ($count == 0) {
    $queue->createQueue();
    foreach ($users as $user) {
      $mail = $user->mail->value;
      if ($mail != $admin_mail) {
        $username = $user->name->value;
        $queue->createItem(['mail' => $mail,'username' => $username]);  
      }
    }
  }
}
